services:
  auth:
    build:
      context: ./auth-service
    environment:
      POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      REDIS_URL: ${REDIS_HOST}:${REDIS_PORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      GIN_MODE: ${GIN_MODE}
    volumes:
      - ./keys:/app/keys:ro
    restart: unless-stopped

  adapter:
    build:
      context: ./smart-home-adapter
    environment:
      POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      MQTT_URL: tcp://broker:1883
      GIN_MODE: ${GIN_MODE}
    depends_on:
      - broker
      - db
    volumes:
      - ./keys:/app/keys:ro
    restart: unless-stopped

  auth-web:
    build:
      context: ./auth-web
    restart: unless-stopped

  web:
    build:
      context: ./web
    restart: unless-stopped

  nginx:
    image: nginx:1.29
    depends_on:
      - auth
      - auth-web
      - adapter
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx
    restart: unless-stopped

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:8.0
    ports:
      - "6379:6379"
    environment:
      TZ: "Europe/Moscow"
    restart: unless-stopped

  broker:
    image: eclipse-mosquitto:2.0.22
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
